version: "3"

services:
  backend:
    build:
      context: backend
    volumes:
      - ./backend:/app
      - ${files}:/home/files
    ports:
      - 5000:5000

  frontend:
    volumes:
      - type: bind
        source: frontend
        target: /app
      - target-cache:/app/target
      - cargo-registry-cache:/usr/local/cargo/registry
    build:
      context: frontend
    command: bash -c "cd app && trunk serve --release --address 0.0.0.0 --port ${TRUNK_SERVE_PORT:-8000}"
    environment:
      - TRUNK_SERVE_PORT=${TRUNK_SERVE_PORT:-80}
    ports:
      - "${TRUNK_SERVE_PORT:-8000}:${TRUNK_SERVE_PORT:-8000}"

volumes:
  target-cache:
  cargo-registry-cache:
