services:
  backend:
    build:
      context: backend
    ports:
      - 5000:5000
    volumes:
      - ${files}:/home/files

  frontend:
    volumes:
      - type: bind
        source: frontend
        target: /app
      - target-cache:/app/target
      - cargo-registry-cache:/usr/local/cargo/registry
    build:
      context: frontend
    command: bash -c "cd app && trunk serve --address 0.0.0.0 --port ${TRUNK_SERVE_PORT:-8000}"
    environment:
      - TRUNK_SERVE_PORT=${TRUNK_SERVE_PORT:-80}
    ports:
      - "${TRUNK_SERVE_PORT:-8000}:${TRUNK_SERVE_PORT:-8000}"
    develop:
      watch:
        - action: rebuild
          path: frontend

volumes:
  target-cache:
  cargo-registry-cache:
